/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HowRouteImport } from './routes/how'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MechanismRouteImport } from './routes/mechanism'
import { Route as NewRouteImport } from './routes/new'
import { Route as SourceRouteImport } from './routes/source'
import { Route as GateIndexRouteImport } from './routes/gate.index'
import { Route as GateIdRouteImport } from './routes/gate.$id'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as PayIndexRouteImport } from './routes/pay.index'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as ApiGateIdRouteImport } from './routes/api/gate.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanismRoute = MechanismRouteImport.update({
  id: '/mechanism',
  path: '/mechanism',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const GateIndexRoute = GateIndexRouteImport.update({
  id: '/gate/',
  path: '/gate/',
  getParentRoute: () => rootRouteImport,
} as any)
const GateIdRoute = GateIdRouteImport.update({
  id: '/gate/$id',
  path: '/gate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIndexRoute = PayIndexRouteImport.update({
  id: '/pay/',
  path: '/pay/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGateIdRoute = ApiGateIdRouteImport.update({
  id: '/api/gate/$id',
  path: '/api/gate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/how': typeof HowRoute
  '/invoices': typeof InvoicesRoute
  '/lab': typeof LabRoute
  '/mechanism': typeof MechanismRoute
  '/new': typeof NewRoute
  '/source': typeof SourceRoute
  '/gate/$id': typeof GateIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/pay/$id': typeof PayIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/gate/': typeof GateIndexRoute
  '/pay/': typeof PayIndexRoute
  '/api/gate/$id': typeof ApiGateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/how': typeof HowRoute
  '/invoices': typeof InvoicesRoute
  '/lab': typeof LabRoute
  '/mechanism': typeof MechanismRoute
  '/new': typeof NewRoute
  '/source': typeof SourceRoute
  '/gate/$id': typeof GateIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/pay/$id': typeof PayIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/gate': typeof GateIndexRoute
  '/pay': typeof PayIndexRoute
  '/api/gate/$id': typeof ApiGateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/how': typeof HowRoute
  '/invoices': typeof InvoicesRoute
  '/lab': typeof LabRoute
  '/mechanism': typeof MechanismRoute
  '/new': typeof NewRoute
  '/source': typeof SourceRoute
  '/gate/$id': typeof GateIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/pay/$id': typeof PayIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/gate/': typeof GateIndexRoute
  '/pay/': typeof PayIndexRoute
  '/api/gate/$id': typeof ApiGateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/demo'
    | '/docs'
    | '/how'
    | '/invoices'
    | '/lab'
    | '/mechanism'
    | '/new'
    | '/source'
    | '/gate/$id'
    | '/invoice/$id'
    | '/pay/$id'
    | '/receipt/$id'
    | '/gate/'
    | '/pay/'
    | '/api/gate/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/demo'
    | '/docs'
    | '/how'
    | '/invoices'
    | '/lab'
    | '/mechanism'
    | '/new'
    | '/source'
    | '/gate/$id'
    | '/invoice/$id'
    | '/pay/$id'
    | '/receipt/$id'
    | '/gate'
    | '/pay'
    | '/api/gate/$id'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/demo'
    | '/docs'
    | '/how'
    | '/invoices'
    | '/lab'
    | '/mechanism'
    | '/new'
    | '/source'
    | '/gate/$id'
    | '/invoice/$id'
    | '/pay/$id'
    | '/receipt/$id'
    | '/gate/'
    | '/pay/'
    | '/api/gate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  HowRoute: typeof HowRoute
  InvoicesRoute: typeof InvoicesRoute
  LabRoute: typeof LabRoute
  MechanismRoute: typeof MechanismRoute
  NewRoute: typeof NewRoute
  SourceRoute: typeof SourceRoute
  GateIdRoute: typeof GateIdRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  PayIdRoute: typeof PayIdRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  GateIndexRoute: typeof GateIndexRoute
  PayIndexRoute: typeof PayIndexRoute
  ApiGateIdRoute: typeof ApiGateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanism': {
      id: '/mechanism'
      path: '/mechanism'
      fullPath: '/mechanism'
      preLoaderRoute: typeof MechanismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate/': {
      id: '/gate/'
      path: '/gate'
      fullPath: '/gate/'
      preLoaderRoute: typeof GateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate/$id': {
      id: '/gate/$id'
      path: '/gate/$id'
      fullPath: '/gate/$id'
      preLoaderRoute: typeof GateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/': {
      id: '/pay/'
      path: '/pay'
      fullPath: '/pay/'
      preLoaderRoute: typeof PayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gate/$id': {
      id: '/api/gate/$id'
      path: '/api/gate/$id'
      fullPath: '/api/gate/$id'
      preLoaderRoute: typeof ApiGateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  HowRoute: HowRoute,
  InvoicesRoute: InvoicesRoute,
  LabRoute: LabRoute,
  MechanismRoute: MechanismRoute,
  NewRoute: NewRoute,
  SourceRoute: SourceRoute,
  GateIdRoute: GateIdRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  PayIdRoute: PayIdRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  GateIndexRoute: GateIndexRoute,
  PayIndexRoute: PayIndexRoute,
  ApiGateIdRoute: ApiGateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
