/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowRouteImport } from './routes/how'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MechanismRouteImport } from './routes/mechanism'
import { Route as NewRouteImport } from './routes/new'
import { Route as SourceRouteImport } from './routes/source'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as PayIdRouteImport } from './routes/pay.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanismRoute = MechanismRouteImport.update({
  id: '/mechanism',
  path: '/mechanism',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/invoices': typeof InvoicesRoute
  '/lab': typeof LabRoute
  '/mechanism': typeof MechanismRoute
  '/new': typeof NewRoute
  '/source': typeof SourceRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/pay/$id': typeof PayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/invoices': typeof InvoicesRoute
  '/lab': typeof LabRoute
  '/mechanism': typeof MechanismRoute
  '/new': typeof NewRoute
  '/source': typeof SourceRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/pay/$id': typeof PayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/invoices': typeof InvoicesRoute
  '/lab': typeof LabRoute
  '/mechanism': typeof MechanismRoute
  '/new': typeof NewRoute
  '/source': typeof SourceRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/pay/$id': typeof PayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how'
    | '/invoices'
    | '/lab'
    | '/mechanism'
    | '/new'
    | '/source'
    | '/invoice/$id'
    | '/pay/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how'
    | '/invoices'
    | '/lab'
    | '/mechanism'
    | '/new'
    | '/source'
    | '/invoice/$id'
    | '/pay/$id'
  id:
    | '__root__'
    | '/'
    | '/how'
    | '/invoices'
    | '/lab'
    | '/mechanism'
    | '/new'
    | '/source'
    | '/invoice/$id'
    | '/pay/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowRoute: typeof HowRoute
  InvoicesRoute: typeof InvoicesRoute
  LabRoute: typeof LabRoute
  MechanismRoute: typeof MechanismRoute
  NewRoute: typeof NewRoute
  SourceRoute: typeof SourceRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  PayIdRoute: typeof PayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanism': {
      id: '/mechanism'
      path: '/mechanism'
      fullPath: '/mechanism'
      preLoaderRoute: typeof MechanismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowRoute: HowRoute,
  InvoicesRoute: InvoicesRoute,
  LabRoute: LabRoute,
  MechanismRoute: MechanismRoute,
  NewRoute: NewRoute,
  SourceRoute: SourceRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  PayIdRoute: PayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
